### PR TITLE
allow email, phonenumber add data to be added when creating a parcel

### PR DESCRIPTION
**Pull request by fatboypunk**
I couldn't find how to add the phone number and email in another way.

Let me know what you think

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
Thanks @fatboypunk,

**Comment by rmachielse** [comment]
@fatboypunk @peterberkenbosch any updates on this? It would be useful to be able to add a phone number and email address, which is now always being overridden.

**Comment by fatboypunk** [comment]
For me my fix is working, haven't really looked into the tests. When needed i could update them

**Comment by rmachielse** [comment]
Thanks for the quick reply! It would be great if that can be arranged. The change looks fine to me, but would prefer to have a release.

**Comment by fatboypunk** [comment]
I stopped working on this because i thought there was another refactor comming up. But i'll look into the test to fix them

**Comment by rmachielse** [comment]
Fantastic!

**Comment by fatboypunk** [comment]
Tests are fixed, please let me know what i can do to get this merged @peterberkenbosch

**Comment by peterberkenbosch** [comment]
Thanks @fatboypunk!

**Comment by rmachielse** [comment]
Thanks guys! Can we also get a release?

**Comment by rmachielse** [comment]
@peterberkenbosch can you also publish a release now that this is merged?

**Comment by rmachielse** [comment]
@peterberkenbosch this pr was merged but is still not in a release. Do you intend to do so soon?

**Pull request merged**
